FROM node:20-slim

WORKDIR /app
COPY package*.json ./
RUN apt-get update && apt-get install -y \
    python3 \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN npm install --legacy-peer-deps
COPY . .

CMD ["npm", "run", "dev"]
